[package]
name = "dioxus-example"
version = "0.0.0"
edition = "2021"

[package.metadata.packager]
format = ["nsis"]
product-name = "Dioxus example"
resources = { "src/*.rs" = "assets" }

[dependencies]
dioxus = "0.4"
dioxus-desktop = "0.4"
