[package]
name = "tauri-example"
version = "0.0.0"
edition = "2021"

[package.metadata.packager]
before-packaging-command = "cargo tauri build"
product-name = "Tauri example"
identifier = "com.tauri.example"
icons = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]

[build-dependencies]
tauri-build = { version = "=2.0.0-alpha.7", features = [] }

[dependencies]
tauri = { version = "=2.0.0-alpha.10", features = [] }
tauri-macros = "=2.0.0-alpha.6"
serde.workspace = true
serde_json.workspace = true

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
